name: Cross-Platform SBT Test
run-name: ${{ github.workflow }} - ${{ github.actor }}
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ["ubuntu-latest", "ubuntu-24.04-arm", "macos-latest", "windows-latest"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 23
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm'
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install verilator
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          base-devel
          mingw-w64-x86_64-verilator
    - name: Add Verilator to PATH
      if: matrix.os == 'windows-latest'
      run: echo "PATH=$PATH:/mingw64/bin" >> $GITHUB_ENV
    - name: Build and Test
      run: |
        verilator --version
        sbt +test