name: Cross-Platform SBT Test
run-name: ${{ github.workflow }} - ${{ github.actor }}
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ["ubuntu-latest", "ubuntu-24.04-arm", "macos-latest", "windows-latest"]
        include:
          - os: ubuntu-latest
            shell: bash
          - os: ubuntu-24.04-arm
            shell: bash
          - os: macos-latest
            shell: bash
          - os: windows-latest
            shell: msys2 {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 23
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm'
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install verilator
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-openjdk
          mingw-w64-x86_64-verilator
    - name: Install sbt manually
      if: matrix.os == 'windows-latest'
      run: |
        curl -L -o sbt.zip https://github.com/sbt/sbt/releases/download/v1.9.7/sbt-1.9.7.zip
        unzip sbt.zip -d /opt
        echo 'export PATH=/opt/sbt/bin:$PATH' >> ~/.bash_profile
        source ~/.bash_profile
        sbt sbtVersion
    - name: Build and Test (Windows)
      if: matrix.os == 'windows-latest'
      shell: msys2 {0}
      run: |
        source ~/.bash_profile
        verilator --version
        sbt +test
    - name: Build and Test (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        verilator --version
        sbt +test