name: Cross-Platform SBT Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ["ubuntu-latest", "macos-latest"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 23
    - name: Setup sbt launcher
      id: setup-sbt
      uses: sbt/setup-sbt@v1
    - name: setup verilator (ubuntu)
      if: matrix.OS == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator
    - name: setup verilator (macos)
      if: matrix.OS == 'macos-latest' 
      run: |
        brew install verilator
    - name: sbt test
      run: |
        sbt test