name: Cross-Platform SBT Test
run-name: ${{ github.workflow }} - ${{ github.actor }}
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ["ubuntu-latest", "ubuntu-24.04-arm", "macos-latest", "windows-latest", "windows-11-arm"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 23
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - name: Build and Test
      run: sbt +test